import type { AssassinMissionCategory, AssassinMissionDifficulty } from "@/types/game";

export const ASSASSIN_MISSION_CATEGORIES: AssassinMissionCategory[] = [
  "Speech",
  "Photo",
  "Object",
  "Location",
  "Social",
  "Funny"
];

export const ASSASSIN_MISSION_DIFFICULTIES: AssassinMissionDifficulty[] = [
  "Easy",
  "Medium",
  "Hard",
  "Epic"
];

export const DEFAULT_ASSASSIN_MISSION_TEMPLATES: Array<{
  key: string;
  title: string;
  text: string;
  difficulty: AssassinMissionDifficulty;
  category: AssassinMissionCategory;
}> = [
  { key: "say-taxi", title: "Say Taxi", text: "Make the target say \"Taxi\".", difficulty: "Easy", category: "Speech" },
  { key: "say-istanbul", title: "Say Istanbul", text: "Make the target say \"Istanbul\".", difficulty: "Easy", category: "Speech" },
  { key: "silly-greeting", title: "Silly Greeting", text: "Make the target greet you with a dramatic bow.", difficulty: "Easy", category: "Speech" },
  { key: "secret-word", title: "Secret Word", text: "Make the target say the word \"pineapple\" before the next conversation ends.", difficulty: "Easy", category: "Speech" },
  { key: "mystery-wave", title: "Mystery Wave", text: "Make the target wave to a stranger as if they are old friends.", difficulty: "Easy", category: "Social" },
  { key: "coffee-corner", title: "Coffee Corner", text: "Make the target stand near the coffee station for at least one minute.", difficulty: "Easy", category: "Location" },
  { key: "tiny-gesture", title: "Tiny Gesture", text: "Make the target hold an object for 10 seconds.", difficulty: "Easy", category: "Object" },
  { key: "color-check", title: "Color Check", text: "Make the target mention the color of their shoes.", difficulty: "Easy", category: "Speech" },
  { key: "tablet-smile", title: "Tablet Smile", text: "Make the target smile at a device screen for 5 seconds.", difficulty: "Easy", category: "Funny" },
  { key: "window-watch", title: "Window Watch", text: "Make the target look out a window and describe what they see.", difficulty: "Easy", category: "Location" },
  { key: "friendly-nod", title: "Friendly Nod", text: "Make the target give you a friendly nod within the next 5 minutes.", difficulty: "Easy", category: "Social" },
  { key: "sneak-selfie", title: "Sneak Selfie", text: "Take a quick selfie together without the target noticing.", difficulty: "Easy", category: "Photo" },
  { key: "backpack-spot", title: "Backpack Spot", text: "Make the target point out someone carrying a backpack.", difficulty: "Easy", category: "Social" },
  { key: "meme-mention", title: "Meme Mention", text: "Make the target mention a meme they recently saw.", difficulty: "Easy", category: "Speech" },
  { key: "chair-friend", title: "Chair Friend", text: "Make the target sit in a different chair than usual for one minute.", difficulty: "Easy", category: "Object" },
  { key: "name-recall", title: "Name Recall", text: "Make the target recall a name from the group and say it out loud.", difficulty: "Easy", category: "Social" },
  { key: "sunny-stance", title: "Sunny Stance", text: "Make the target stand in the sun for 10 seconds and pretend it is intentional.", difficulty: "Easy", category: "Location" },
  { key: "book-bounce", title: "Book Bounce", text: "Make the target briefly tap a book, magazine, or notebook.", difficulty: "Easy", category: "Object" },
  { key: "snack-spot", title: "Snack Spot", text: "Make the target point to the nearest snack item.", difficulty: "Easy", category: "Location" },
  { key: "hero-pose", title: "Hero Pose", text: "Make the target strike a dramatic hero pose for 3 seconds.", difficulty: "Easy", category: "Funny" },
  { key: "selfie", title: "Selfie Together", text: "Take a selfie with the target.", difficulty: "Medium", category: "Photo" },
  { key: "hold-sunglasses", title: "Hold Sunglasses", text: "Make the target hold your sunglasses.", difficulty: "Medium", category: "Object" },
  { key: "bench", title: "Bench Sit", text: "Make the target sit on a bench with you.", difficulty: "Medium", category: "Location" },
  { key: "ask-question", title: "Ask Question", text: "Make the target ask a stranger for directions.", difficulty: "Medium", category: "Social" },
  { key: "tourist-pose", title: "Tourist Pose", text: "Make the target recreate a tourist pose.", difficulty: "Medium", category: "Funny" },
  { key: "shadow-walk", title: "Shadow Walk", text: "Make the target walk beside you in a perfectly synchronized stride for 20 seconds.", difficulty: "Medium", category: "Location" },
  { key: "camera-glance", title: "Camera Glance", text: "Make the target glance at the nearest camera and act mysterious for a beat.", difficulty: "Medium", category: "Photo" },
  { key: "lunch-story", title: "Lunch Story", text: "Make the target tell a short story about lunch in the next 5 minutes.", difficulty: "Medium", category: "Speech" },
  { key: "mystery-raise", title: "Mystery Raise", text: "Make the target raise one eyebrow at you.", difficulty: "Medium", category: "Funny" },
  { key: "table-trick", title: "Table Trick", text: "Make the target arrange a small object into a neat line on a table.", difficulty: "Medium", category: "Object" },
  { key: "group-balance", title: "Group Balance", text: "Make the target stand with at least two other people in one photo frame.", difficulty: "Medium", category: "Photo" },
  { key: "secret-compliment", title: "Secret Compliment", text: "Make the target give a sincere compliment to someone nearby.", difficulty: "Medium", category: "Social" },
  { key: "passport-pose", title: "Passport Pose", text: "Make the target pretend to check a passport in a dramatic way.", difficulty: "Medium", category: "Funny" },
  { key: "fountain-focus", title: "Fountain Focus", text: "Make the target stand near a fountain or water feature for one minute.", difficulty: "Medium", category: "Location" },
  { key: "window-signal", title: "Window Signal", text: "Make the target point at a window and call it a secret portal.", difficulty: "Medium", category: "Funny" },
  { key: "drink-order", title: "Drink Order", text: "Make the target order a drink with a ridiculous but harmless name.", difficulty: "Medium", category: "Social" },
  { key: "pocket-check", title: "Pocket Check", text: "Make the target check their pocket and announce what they found.", difficulty: "Medium", category: "Object" },
  { key: "umbrella-plot", title: "Umbrella Plot", text: "Make the target hold an umbrella or bag like a detective for 10 seconds.", difficulty: "Medium", category: "Object" },
  { key: "street-name", title: "Street Name", text: "Make the target say the name of the nearest street or landmark.", difficulty: "Medium", category: "Speech" },
  { key: "sneaky-laugh", title: "Sneaky Laugh", text: "Make the target laugh at a harmless joke told by you.", difficulty: "Medium", category: "Social" },
  { key: "secret-selfie", title: "Secret Selfie", text: "Get a selfie with the target without them noticing.", difficulty: "Hard", category: "Photo" },
  { key: "buy-drink", title: "Buy Drink", text: "Make the target buy you a drink.", difficulty: "Hard", category: "Social" },
  { key: "spy-phrase", title: "Spy Phrase", text: "Get the target to use a coded phrase like \"Mission accepted\" in the next 10 minutes.", difficulty: "Hard", category: "Speech" },
  { key: "mystery-photo", title: "Mystery Photo", text: "Get a picture of the target while they are trying not to smile.", difficulty: "Hard", category: "Photo" },
  { key: "table-ritual", title: "Table Ritual", text: "Make the target perform a tiny ritual such as tapping a table twice before sitting down.", difficulty: "Hard", category: "Object" },
  { key: "service-smile", title: "Service Smile", text: "Make the target smile at a staff member and thank them for something small.", difficulty: "Hard", category: "Social" },
  { key: "sneaky-collect", title: "Sneaky Collect", text: "Have the target collect a small item, such as a coaster or napkin, and hand it to you.", difficulty: "Hard", category: "Object" },
  { key: "leader-quote", title: "Leader Quote", text: "Make the target quote a famous line from a movie or song without being asked.", difficulty: "Hard", category: "Speech" },
  { key: "bridge-walk", title: "Bridge Walk", text: "Walk with the target to a landmark and make them explain why it matters.", difficulty: "Hard", category: "Location" },
  { key: "captain-gesture", title: "Captain Gesture", text: "Make the target salute a harmless object as if it were their commander.", difficulty: "Hard", category: "Funny" },
  { key: "camera-plot", title: "Camera Plot", text: "Make the target pose as if they are in a spy movie for 15 seconds.", difficulty: "Hard", category: "Photo" },
  { key: "puzzle-prompt", title: "Puzzle Prompt", text: "Ask the target to solve a harmless riddle or tiny puzzle.", difficulty: "Hard", category: "Social" },
  { key: "statue-chat", title: "Statue Chat", text: "Make the target talk to a statue, sculpture, or decorative object for 10 seconds.", difficulty: "Hard", category: "Location" },
  { key: "map-mission", title: "Map Mission", text: "Make the target use a map or guide and explain the route to you.", difficulty: "Hard", category: "Location" },
  { key: "chair-royalty", title: "Chair Royalty", text: "Make the target sit in a chair and act as if they are royalty for 10 seconds.", difficulty: "Hard", category: "Funny" },
  { key: "group-photo", title: "Epic Group Photo", text: "Get the entire group into a photo without revealing your mission.", difficulty: "Epic", category: "Photo" },
  { key: "legendary-gesture", title: "Legendary Gesture", text: "Make the target perform a dramatic handshake with a stranger that feels like a movie scene.", difficulty: "Epic", category: "Social" },
  { key: "secret-agent", title: "Secret Agent", text: "Get the target to follow a simple secret-agent style instruction without explaining why.", difficulty: "Epic", category: "Funny" },
  { key: "story-circle", title: "Story Circle", text: "Get the target to tell a complete story involving at least three people from the group.", difficulty: "Epic", category: "Speech" },
  { key: "mystic-spot", title: "Mystic Spot", text: "Guide the target to a landmark and make them announce it like a discovery.", difficulty: "Epic", category: "Location" },
  { key: "crown-toast", title: "Crown Toast", text: "Make the target give a toast to the group using a silly but safe title.", difficulty: "Epic", category: "Social" },
  { key: "unseen-pose", title: "Unseen Pose", text: "Get the target to pose for an image while pretending they are in a spy film.", difficulty: "Epic", category: "Photo" },
  { key: "treasure-riddle", title: "Treasure Riddle", text: "Make the target solve a harmless riddle and explain the answer to you.", difficulty: "Epic", category: "Social" },
  { key: "duo-stance", title: "Duo Stance", text: "Get the target to stand beside you in a dramatic duo pose for 15 seconds.", difficulty: "Epic", category: "Photo" },
  { key: "grand-intro", title: "Grand Introduction", text: "Make the target introduce you to someone new with a grand, fictional title.", difficulty: "Epic", category: "Social" },
  { key: "rain-check", title: "Rain Check", text: "Make the target announce the weather like a weather presenter.", difficulty: "Easy", category: "Speech" },
  { key: "hashtag-hint", title: "Hashtag Hint", text: "Make the target mention a harmless hashtag in the next 5 minutes.", difficulty: "Easy", category: "Social" },
  { key: "shoe-shine", title: "Shoe Shine", text: "Make the target point to their shoes and call them elegant.", difficulty: "Easy", category: "Object" },
  { key: "door-knock", title: "Door Knock", text: "Make the target knock on a nearby door or surface once.", difficulty: "Easy", category: "Object" },
  { key: "calendar-glance", title: "Calendar Glance", text: "Make the target glance at a calendar and comment on the date.", difficulty: "Easy", category: "Location" },
  { key: "tiny-breath", title: "Tiny Breath", text: "Make the target take one dramatic breath before speaking.", difficulty: "Easy", category: "Funny" },
  { key: "pocket-rhyme", title: "Pocket Rhyme", text: "Make the target say a simple rhyme with a nearby object.", difficulty: "Easy", category: "Speech" },
  { key: "cactus-claim", title: "Cactus Claim", text: "Make the target pretend a plant is a secret agent for 10 seconds.", difficulty: "Easy", category: "Funny" },
  { key: "friendly-wave", title: "Friendly Wave", text: "Make the target wave at a passing person as if they know them.", difficulty: "Easy", category: "Social" },
  { key: "badge-spot", title: "Badge Spot", text: "Make the target point out a badge, logo, or sticker nearby.", difficulty: "Easy", category: "Location" },
  { key: "paper-fold", title: "Paper Fold", text: "Make the target fold a piece of paper once and hand it to you.", difficulty: "Easy", category: "Object" },
  { key: "mug-raise", title: "Mug Raise", text: "Make the target raise a mug as if giving a tiny toast.", difficulty: "Easy", category: "Object" },
  { key: "lantern-look", title: "Lantern Look", text: "Make the target look at a lamp or lantern and comment on it.", difficulty: "Easy", category: "Location" },
  { key: "watch-check", title: "Watch Check", text: "Make the target check a watch or phone clock for a moment.", difficulty: "Easy", category: "Object" },
  { key: "shadow-echo", title: "Shadow Echo", text: "Make the target repeat your final word for a laugh.", difficulty: "Easy", category: "Speech" },
  { key: "hat-tap", title: "Hat Tap", text: "Make the target tap a hat or cap once as if it were a signal.", difficulty: "Easy", category: "Object" },
  { key: "greeting-gesture", title: "Greeting Gesture", text: "Make the target salute a friendly greeting to someone nearby.", difficulty: "Easy", category: "Social" },
  { key: "sun-glance", title: "Sun Glance", text: "Make the target look at the sun and comment on the light.", difficulty: "Easy", category: "Location" },
  { key: "map-point", title: "Map Point", text: "Make the target point to the nearest map or guide for 5 seconds.", difficulty: "Easy", category: "Location" },
  { key: "pocket-drum", title: "Pocket Drum", text: "Make the target tap a pocket once as if it were a drum.", difficulty: "Easy", category: "Object" },
  { key: "museum-glance", title: "Museum Glance", text: "Make the target act like they are examining a display for 10 seconds.", difficulty: "Medium", category: "Location" },
  { key: "mirror-smile", title: "Mirror Smile", text: "Make the target smile at a reflection or mirror for a moment.", difficulty: "Medium", category: "Funny" },
  { key: "travel-story", title: "Travel Story", text: "Make the target tell a short story about a recent trip.", difficulty: "Medium", category: "Speech" },
  { key: "tiny-compliment", title: "Tiny Compliment", text: "Make the target give a sincere compliment to the nearest person.", difficulty: "Medium", category: "Social" },
  { key: "mystery-pause", title: "Mystery Pause", text: "Make the target pause, look around, and say \"interesting\".", difficulty: "Medium", category: "Speech" },
  { key: "photo-frame", title: "Photo Frame", text: "Make the target stand in a way that looks like a picture frame.", difficulty: "Medium", category: "Photo" },
  { key: "suitcase-scan", title: "Suitcase Scan", text: "Make the target inspect a bag or suitcase as if it were valuable.", difficulty: "Medium", category: "Object" },
  { key: "queue-quote", title: "Queue Quote", text: "Make the target say a line from a movie while in a queue.", difficulty: "Medium", category: "Speech" },
  { key: "neon-nod", title: "Neon Nod", text: "Make the target nod at a neon sign or bright display.", difficulty: "Medium", category: "Location" },
  { key: "cup-gesture", title: "Cup Gesture", text: "Make the target hold a cup with a dramatic flourish.", difficulty: "Medium", category: "Object" },
  { key: "sneak-signal", title: "Sneak Signal", text: "Make the target give you a tiny secret signal with a hand gesture.", difficulty: "Medium", category: "Social" },
  { key: "park-pose", title: "Park Pose", text: "Make the target pose as if they are about to start a dramatic speech.", difficulty: "Medium", category: "Funny" },
  { key: "stair-story", title: "Stair Story", text: "Make the target tell a brief story while standing on a staircase.", difficulty: "Medium", category: "Location" },
  { key: "chair-spot", title: "Chair Spot", text: "Make the target point out the most interesting chair nearby.", difficulty: "Medium", category: "Object" },
  { key: "breeze-comment", title: "Breeze Comment", text: "Make the target comment on the breeze or weather for 10 seconds.", difficulty: "Medium", category: "Speech" },
  { key: "coaster-collect", title: "Coaster Collect", text: "Make the target pick up a coaster and place it back carefully.", difficulty: "Medium", category: "Object" },
  { key: "group-smile", title: "Group Smile", text: "Make the target smile at two other people in the group at once.", difficulty: "Medium", category: "Social" },
  { key: "ticket-tap", title: "Ticket Tap", text: "Make the target tap a ticket, card, or pass once for effect.", difficulty: "Medium", category: "Object" },
  { key: "lobby-look", title: "Lobby Look", text: "Make the target look around a lobby and announce what they notice.", difficulty: "Medium", category: "Location" },
  { key: "mood-quote", title: "Mood Quote", text: "Make the target quote a safe one-line saying from a famous quote.", difficulty: "Medium", category: "Speech" },
  { key: "spectator-speech", title: "Spectator Speech", text: "Make the target address a nearby spectator as if they are an audience.", difficulty: "Hard", category: "Social" },
  { key: "glass-ritual", title: "Glass Ritual", text: "Make the target tap a glass or cup twice before drinking.", difficulty: "Hard", category: "Object" },
  { key: "mystery-review", title: "Mystery Review", text: "Have the target review a nearby object as if it were a product.", difficulty: "Hard", category: "Social" },
  { key: "curator-claim", title: "Curator Claim", text: "Make the target announce that they are the curator of a nearby space.", difficulty: "Hard", category: "Funny" },
  { key: "sound-check", title: "Sound Check", text: "Make the target perform a harmless sound check before speaking.", difficulty: "Hard", category: "Speech" },
  { key: "photo-guard", title: "Photo Guard", text: "Get the target to protect a photo or screen from accidental bumps.", difficulty: "Hard", category: "Photo" },
  { key: "lantern-order", title: "Lantern Order", text: "Make the target give a small object a dramatic order and obey it.", difficulty: "Hard", category: "Funny" },
  { key: "table-forecast", title: "Table Forecast", text: "Make the target predict what will happen next to a table or object.", difficulty: "Hard", category: "Object" },
  { key: "passport-plot", title: "Passport Plot", text: "Make the target explain a harmless passport or travel plan like a spy.", difficulty: "Hard", category: "Speech" },
  { key: "staff-thanks", title: "Staff Thanks", text: "Make the target thank a staff member for a tiny and ordinary service.", difficulty: "Hard", category: "Social" },
  { key: "window-judge", title: "Window Judge", text: "Make the target judge a window, frame, or view like an expert.", difficulty: "Hard", category: "Location" },
  { key: "map-command", title: "Map Command", text: "Have the target point at a map and give a safe command to the group.", difficulty: "Hard", category: "Location" },
  { key: "napkin-legend", title: "Napkin Legend", text: "Make the target treat a napkin or paper item like a legendary artifact.", difficulty: "Hard", category: "Object" },
  { key: "crown-speech", title: "Crown Speech", text: "Make the target give a short speech as if they are holding a tiny crown.", difficulty: "Hard", category: "Funny" },
  { key: "camera-guard", title: "Camera Guard", text: "Make the target pose as a bodyguard for a camera or phone for 15 seconds.", difficulty: "Hard", category: "Photo" },
  { key: "star-spotter", title: "Star Spotter", text: "Get the target to announce a star, symbol, or sign they notice nearby.", difficulty: "Epic", category: "Location" },
  { key: "legendary-toast", title: "Legendary Toast", text: "Make the target give a dramatic toast to the group with a made-up title.", difficulty: "Epic", category: "Social" },
  { key: "shadow-director", title: "Shadow Director", text: "Get the target to direct a harmless scene as if they are a movie director.", difficulty: "Epic", category: "Funny" },
  { key: "story-quest", title: "Story Quest", text: "Have the target tell a complete story involving a quest, a clue, and a twist.", difficulty: "Epic", category: "Speech" },
  { key: "suspicious-glance", title: "Suspicious Glance", text: "Make the target glance around like a spy and then explain the situation.", difficulty: "Epic", category: "Photo" },
  { key: "royal-wave", title: "Royal Wave", text: "Make the target perform a regal wave to the group for 10 seconds.", difficulty: "Epic", category: "Social" },
  { key: "artifact-hunt", title: "Artifact Hunt", text: "Guide the target to a harmless object and make them announce it like treasure.", difficulty: "Epic", category: "Location" },
  { key: "camera-commander", title: "Camera Commander", text: "Make the target give a dramatic command to a camera or phone.", difficulty: "Epic", category: "Photo" },
  { key: "grand-riddle", title: "Grand Riddle", text: "Have the target solve a silly riddle and explain the answer like a legend.", difficulty: "Epic", category: "Social" },
  { key: "duo-legend", title: "Duo Legend", text: "Make the target stand beside you in a grand duo pose for 20 seconds.", difficulty: "Epic", category: "Photo" }
];
